### PR TITLE
Move to MIT License

### PR DESCRIPTION
**Pull request by aaronosher**
Personally, I'm partial to MIT Licences, especially when I struggle to justify the something as strict as the GPL. Particularly, considering this is a website for a Hackathon.

However, @jamietanna does make a good point in #16 it would be best to get permission from past contributors.

So, @harrymt @jamietanna @Casper-Oakley @jonathanballs @JamesMCo, if you're chill with moving it, just react with a 👍

### CODE REVIEW

**Comment by jamietanna** [comment]
+1 on choosealicense but also recommend tldrlegal.com for easier-to-consume legalise

**Comment by jamietanna** [comment]
Also tagging @johnathan99j for approval

**Comment by aaronosher** [comment]
@johnathan99j that's fair. I'm mainly looking for @harrymt and @JamesMCo thoughts at this point, as if either of them are opposed to the change, I'll leave it to move to the AGPL instead.

**Comment by JamesMCo** [comment]
I don't think I'm as invested in this as the rest of you guys. Any of the proposed options sound like they'd be good 🙂

**Comment by harrymt** [comment]
I am happy to go with whatever you think is best @aaronosher 😄

**Pull request closed without merging**
